### ISSUE TITLE
Add .charles.yml support

### ISSUE THREAD

**Issue by amihaiemil** [amihaiemil/charles-github-ejb#208]
We should offer the possibility of adding the ``.charles.yml`` configuration file.
For starters, let's offer a way of specifying commanders and tweet option:

```yaml
commanders:
  - amihaiemil
  - johndoe
  - otherguy
tweet: true
...
```
